"""Фасад хендлеров: раньше это был app/handlers.py (однобокий монолит ~3300
строк), теперь — пакет из доменных модулей. Единый кнопочный роутер живёт в
common; ПОРЯДОК ИМПОРТА модулей здесь = порядок регистрации хендлеров в
исходном файле, поэтому домены перечислены строго последовательно и
on_private_fallback импортируется ПОСЛЕДНИМ — он ловит любое ЛС и не должен
перехватывать команды.

Для обратной совместимости все публичные имена (и приватные, что используют
тесты и main.py) переэкспортируются отсюда же.
"""
from __future__ import annotations

__all__ = [
    "_ACTIVE_STATUSES",
    "_ADJ_CONFIRM_WINDOW",
    "_DYOR_TEXT",
    "_LAST_UPDATE_ERROR_ALERT",
    "_MONTH_NAMES_RU",
    "_PLAYER_ERROR_TEXT",
    "_STAKE_HOWTO",
    "_UPDATE_ERROR_ALERT_COOLDOWN",
    "_WALLET_COOLDOWN",
    "_WALLET_FALLBACK_TEXT",
    "_active_round_money_mode",
    "_adjust_confirm_text",
    "_adjust_keyboard",
    "_adjust_menu_text",
    "_admin_panel_text",
    "_apply_adjustment",
    "_bind_wallet",
    "_cmd_wallet_impl",
    "_commands_help",
    "_dialog_close",
    "_dialog_open",
    "_dialog_start",
    "_economy_text",
    "_ensure_round",
    "_format_top",
    "_game_paused_now",
    "_human_claim_period",
    "_on_claim",
    "_panel_keyboard",
    "_payouts_text",
    "_pct_text",
    "_personal_keyboard",
    "_refunds_panel_text",
    "_register_error_handler",
    "_resolve_player_arg",
    "_revenue_text",
    "_revote_gram_ceiling",
    "_revote_keyboard",
    "_revote_status",
    "_score_text",
    "_set_paused_and_broadcast",
    "_stake_pay_keyboard",
    "_stake_view_safe",
    "_stake_view_text",
    "_stakes_panel_text",
    "_start_keyboard",
    "_today_stake_line",
    "_wallet_throttled",
    "_wallet_verify_code",
    "_wallet_view_safe",
    "_wallet_view_text",
    "_win_calc_text",
    "build_dispatcher",
    "cmd_adjust",
    "cmd_advance",
    "cmd_change",
    "cmd_dispute",
    "cmd_disputes",
    "cmd_fund",
    "cmd_fundout",
    "cmd_help",
    "cmd_incoming",
    "cmd_invite",
    "cmd_panel",
    "cmd_pause",
    "cmd_payout",
    "cmd_payouts",
    "cmd_referral",
    "cmd_resetgame",
    "cmd_resume",
    "cmd_return",
    "cmd_revenue",
    "cmd_score",
    "cmd_stake",
    "cmd_stakes",
    "cmd_start",
    "cmd_today",
    "cmd_top",
    "cmd_treasury",
    "cmd_wallet",
    "create_bot",
    "handle_update_error",
    "on_adjust_action",
    "on_claim_month",
    "on_claim_week",
    "on_change_view",
    "on_dm_toggle",
    "on_noop",
    "on_panel_action",
    "on_paystars",
    "on_payton",
    "on_pre_checkout",
    "on_private_fallback",
    "on_refunded_payment",
    "on_score_view",
    "on_stake_copy",
    "on_stake_view",
    "on_successful_payment",
    "on_vote",
    "on_wallet_view",
    "router",
    "track_chat",
]

import time as time

from .admin import (
    _ACTIVE_STATUSES,
    _ADJ_CONFIRM_WINDOW,
    _adjust_confirm_text,
    _adjust_keyboard,
    _adjust_menu_text,
    _apply_adjustment,
    _resolve_player_arg,
    cmd_adjust,
    cmd_advance,
    cmd_dispute,
    cmd_disputes,
    cmd_pause,
    cmd_resetgame,
    cmd_resume,
    on_adjust_action,
    track_chat,
)
from .bootstrap import (
    _LAST_UPDATE_ERROR_ALERT,
    _PLAYER_ERROR_TEXT,
    _UPDATE_ERROR_ALERT_COOLDOWN,
    _register_error_handler,
    build_dispatcher,
    create_bot,
    handle_update_error,
)
from .common import (
    _DYOR_TEXT,
    _active_round_money_mode,
    _dialog_close,
    _dialog_open,
    _dialog_start,
    _ensure_round,
    _game_paused_now,
    _personal_keyboard,
    _set_paused_and_broadcast,
    router,
)
from .fallback import on_private_fallback
from .panel import (
    _admin_panel_text,
    _panel_keyboard,
    cmd_panel,
    on_panel_action,
)
from .payout import (
    _payouts_text,
    _refunds_panel_text,
    _revenue_text,
    _stakes_panel_text,
    cmd_fundout,
    cmd_incoming,
    cmd_payout,
    cmd_payouts,
    cmd_return,
    cmd_revenue,
    cmd_stakes,
    cmd_treasury,
)
from .player import (
    _MONTH_NAMES_RU,
    _commands_help,
    _human_claim_period,
    _on_claim,
    _score_text,
    _start_keyboard,
    cmd_help,
    cmd_invite,
    cmd_referral,
    cmd_score,
    cmd_start,
    cmd_today,
    on_claim_month,
    on_claim_week,
    on_dm_toggle,
    on_noop,
    on_score_view,
    on_vote,
)
from .topup import (
    _revote_gram_ceiling,
    _revote_keyboard,
    _revote_status,
    cmd_change,
    on_change_view,
    on_paystars,
    on_payton,
    on_pre_checkout,
    on_refunded_payment,
    on_successful_payment,
)
from .wallet import (
    _STAKE_HOWTO,
    _WALLET_COOLDOWN,
    _WALLET_FALLBACK_TEXT,
    _bind_wallet,
    _cmd_wallet_impl,
    _economy_text,
    _format_top,
    _pct_text,
    _stake_pay_keyboard,
    _stake_view_safe,
    _stake_view_text,
    _today_stake_line,
    _wallet_throttled,
    _wallet_verify_code,
    _wallet_view_safe,
    _wallet_view_text,
    _win_calc_text,
    cmd_fund,
    cmd_stake,
    cmd_top,
    cmd_wallet,
    on_stake_copy,
    on_stake_view,
    on_wallet_view,
)
