"""squash 2: синхронизация с текущими моделями

Revision ID: 11f41c6ba244
Revises: 917223d866c0
Create Date: 2026-09-13 19:20:09.090963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f41c6ba244'
down_revision: Union[str, Sequence[str], None] = '917223d866c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_generated_pools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pool_type', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_generated_pools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_generated_pools_pool_type'), ['pool_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_generated_pools_season'), ['season'], unique=False)

    op.create_table('bestiary_sightings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.String(length=16), nullable=False),
    sa.Column('beast_key', sa.String(length=32), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'beast_key', name='uq_bestiary_season_beast')
    )
    op.create_table('consequence_branches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_key', sa.String(length=64), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('history_json', sa.Text(), nullable=False),
    sa.Column('created_day', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('stage_text', sa.Text(), nullable=False),
    sa.Column('choices_json', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consequence_branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consequence_branches_branch_key'), ['branch_key'], unique=False)

    op.create_table('disputes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('keeper_note', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disputes_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_round_id'), ['round_id'], unique=False)

    op.create_table('dog_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dog_key', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('scar_key', sa.String(length=64), nullable=False),
    sa.Column('created_day', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('surfaced_day', sa.Integer(), nullable=True),
    sa.Column('healed_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dog_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dog_memories_created_day'), ['created_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_dog_memories_dog_key'), ['dog_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_dog_memories_scar_key'), ['scar_key'], unique=False)

    op.create_table('emotional_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fatigue', sa.Integer(), nullable=False),
    sa.Column('hope', sa.Integer(), nullable=False),
    sa.Column('paranoia', sa.Integer(), nullable=False),
    sa.Column('last_updated_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_hits',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('player_id', 'round_id')
    )
    op.create_table('npc_motives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('npc_key', sa.String(length=32), nullable=False),
    sa.Column('mood', sa.String(length=16), nullable=False),
    sa.Column('motive_text', sa.Text(), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('thought_pool_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('npc_motives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_npc_motives_npc_key'), ['npc_key'], unique=False)

    op.create_table('npc_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('npc_key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('speech_style', sa.Text(), nullable=False),
    sa.Column('appearance', sa.Text(), nullable=False),
    sa.Column('default_mood', sa.String(length=16), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('npc_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_npc_profiles_npc_key'), ['npc_key'], unique=True)

    op.create_table('pack_fund',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nanotons', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pack_fund_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_type', sa.String(length=8), nullable=False),
    sa.Column('amount_nanotons', sa.BigInteger(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pack_fund_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pack_fund_ledger_round_id'), ['round_id'], unique=False)

    op.create_table('prologue_beats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('block', sa.Text(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prologue_beats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prologue_beats_season'), ['season'], unique=False)

    op.create_table('referrals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=False),
    sa.Column('referred_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_id')
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referrals_referrer_id'), ['referrer_id'], unique=False)

    op.create_table('season_arcs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('tone', sa.Text(), nullable=False),
    sa.Column('missions_json', sa.Text(), nullable=False),
    sa.Column('whisper_json', sa.Text(), nullable=False),
    sa.Column('teaser_json', sa.Text(), nullable=False),
    sa.Column('guest', sa.Text(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('season_arcs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_season_arcs_season'), ['season'], unique=False)

    op.create_table('weekly_pots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week', sa.String(length=16), nullable=False),
    sa.Column('nanotons', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week')
    )
    op.create_table('world_characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('flaw', sa.Text(), nullable=False),
    sa.Column('virtue', sa.Text(), nullable=False),
    sa.Column('moral_alignment', sa.String(length=32), nullable=False),
    sa.Column('mood', sa.String(length=32), nullable=False),
    sa.Column('trust_stay', sa.Integer(), nullable=False),
    sa.Column('created_day', sa.Integer(), nullable=False),
    sa.Column('last_seen_day', sa.Integer(), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('world_choices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('choice_text', sa.Text(), nullable=False),
    sa.Column('choice_tag', sa.String(length=32), nullable=False),
    sa.Column('consequences_json', sa.Text(), nullable=False),
    sa.Column('characters_involved', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('votes_count', sa.Integer(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world_choices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_choices_day_index'), ['day_index'], unique=False)

    op.create_table('world_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('characters_involved', sa.Text(), nullable=False),
    sa.Column('locations_involved', sa.Text(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_events_day_index'), ['day_index'], unique=False)

    op.create_table('world_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('atmosphere', sa.Text(), nullable=False),
    sa.Column('dangers', sa.Text(), nullable=False),
    sa.Column('resources', sa.Text(), nullable=False),
    sa.Column('created_day', sa.Integer(), nullable=False),
    sa.Column('last_visited_day', sa.Integer(), nullable=True),
    sa.Column('times_visited', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('world_scars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scar_key', sa.String(length=64), nullable=False),
    sa.Column('created_day', sa.Integer(), nullable=False),
    sa.Column('expires_day', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world_scars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_scars_scar_key'), ['scar_key'], unique=False)

    op.create_table('world_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('mood', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('active_locations', sa.Text(), nullable=False),
    sa.Column('active_characters', sa.Text(), nullable=False),
    sa.Column('open_threads', sa.Text(), nullable=False),
    sa.Column('world_trend', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_index')
    )
    op.create_table('leaderboard_claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'kind', 'period', name='uq_leaderboard_claims_player_kind_period')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_cost', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('water_cost', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('health_risk', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('trust_change', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('emotional_consequence', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('npc_reactions_json', sa.Text(), nullable=False))

    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('network', sa.String(length=16), nullable=False))

    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_error', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('comment_override', sa.String(length=120), nullable=True))
        batch_op.create_index('ix_payout_alert', ['status', 'network', 'alerted'], unique=False)
        batch_op.create_index('ix_payout_dispatch', ['status', 'network', 'dest_address'], unique=False)
        batch_op.create_check_constraint('ck_payout_positive_amount', 'amount_nanotons > 0')
        batch_op.create_check_constraint('ck_payout_valid_status', "status IN ('pending', 'sending', 'sent', 'failed', 'dismissed')")

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('wallet_verify_code', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('wallet_verify_created', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('calling', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('inspiration', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('dm_subscribed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('current_streak', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('best_streak', sa.Integer(), nullable=False))

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sealed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('tie_note', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('season', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('place', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('weekly_nanotons', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('money_mode', sa.Boolean(), nullable=False))
        batch_op.create_index('ix_round_status_finalized', ['status', 'payouts_finalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_rounds_season'), ['season'], unique=False)

    with op.batch_alter_table('stakes', schema=None) as batch_op:
        batch_op.create_index('ix_stake_network_round_status', ['network', 'round_id', 'status'], unique=False)
        batch_op.create_unique_constraint('uq_stake_tx_network', ['tx_hash', 'network'])
        batch_op.create_check_constraint('ck_stake_positive_amount', 'amount_nanotons > 0')
        batch_op.create_check_constraint('ck_stake_valid_status', "status IN ('pending', 'confirmed', 'rejected', 'refunded')")

    with op.batch_alter_table('story_beats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hook_text', sa.String(length=700), nullable=True))

    with op.batch_alter_table('watcher_state', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watcher_state', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('story_beats', schema=None) as batch_op:
        batch_op.drop_column('hook_text')

    with op.batch_alter_table('stakes', schema=None) as batch_op:
        batch_op.drop_constraint('ck_stake_valid_status', type_='check')
        batch_op.drop_constraint('ck_stake_positive_amount', type_='check')
        batch_op.drop_constraint('uq_stake_tx_network', type_='unique')
        batch_op.drop_index('ix_stake_network_round_status')

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rounds_season'))
        batch_op.drop_index('ix_round_status_finalized')
        batch_op.drop_column('money_mode')
        batch_op.drop_column('weekly_nanotons')
        batch_op.drop_column('place')
        batch_op.drop_column('season')
        batch_op.drop_column('tie_note')
        batch_op.drop_column('sealed')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('best_streak')
        batch_op.drop_column('current_streak')
        batch_op.drop_column('dm_subscribed')
        batch_op.drop_column('inspiration')
        batch_op.drop_column('calling')
        batch_op.drop_column('wallet_verify_created')
        batch_op.drop_column('wallet_verify_code')
        batch_op.drop_column('wallet_verified')

    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_constraint('ck_payout_valid_status', type_='check')
        batch_op.drop_constraint('ck_payout_positive_amount', type_='check')
        batch_op.drop_index('ix_payout_dispatch')
        batch_op.drop_index('ix_payout_alert')
        batch_op.drop_column('comment_override')
        batch_op.drop_column('last_error')

    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.drop_column('network')

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('npc_reactions_json')
        batch_op.drop_column('emotional_consequence')
        batch_op.drop_column('trust_change')
        batch_op.drop_column('health_risk')
        batch_op.drop_column('water_cost')
        batch_op.drop_column('food_cost')

    op.drop_table('leaderboard_claims')
    op.drop_table('world_snapshots')
    with op.batch_alter_table('world_scars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_scars_scar_key'))

    op.drop_table('world_scars')
    op.drop_table('world_locations')
    with op.batch_alter_table('world_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_events_day_index'))

    op.drop_table('world_events')
    with op.batch_alter_table('world_choices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_choices_day_index'))

    op.drop_table('world_choices')
    op.drop_table('world_characters')
    op.drop_table('weekly_pots')
    with op.batch_alter_table('season_arcs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_season_arcs_season'))

    op.drop_table('season_arcs')
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_referrer_id'))

    op.drop_table('referrals')
    with op.batch_alter_table('prologue_beats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prologue_beats_season'))

    op.drop_table('prologue_beats')
    with op.batch_alter_table('pack_fund_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pack_fund_ledger_round_id'))

    op.drop_table('pack_fund_ledger')
    op.drop_table('pack_fund')
    with op.batch_alter_table('npc_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_npc_profiles_npc_key'))

    op.drop_table('npc_profiles')
    with op.batch_alter_table('npc_motives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_npc_motives_npc_key'))

    op.drop_table('npc_motives')
    op.drop_table('memory_hits')
    op.drop_table('emotional_state')
    with op.batch_alter_table('dog_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dog_memories_scar_key'))
        batch_op.drop_index(batch_op.f('ix_dog_memories_dog_key'))
        batch_op.drop_index(batch_op.f('ix_dog_memories_created_day'))

    op.drop_table('dog_memories')
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disputes_round_id'))
        batch_op.drop_index(batch_op.f('ix_disputes_player_id'))

    op.drop_table('disputes')
    with op.batch_alter_table('consequence_branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consequence_branches_branch_key'))

    op.drop_table('consequence_branches')
    op.drop_table('bestiary_sightings')
    with op.batch_alter_table('ai_generated_pools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_generated_pools_season'))
        batch_op.drop_index(batch_op.f('ix_ai_generated_pools_pool_type'))

    op.drop_table('ai_generated_pools')
    # ### end Alembic commands ###
