"""drop orphan world tables and dead card columns

Revision ID: 2d4f3fbc1a33
Revises: 11f41c6ba244
Create Date: 2026-09-15 10:13:42.881393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4f3fbc1a33'
down_revision: Union[str, Sequence[str], None] = '11f41c6ba244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('world_characters')
    with op.batch_alter_table('world_scars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_scars_scar_key'))

    op.drop_table('world_scars')
    with op.batch_alter_table('npc_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_npc_profiles_npc_key'))

    op.drop_table('npc_profiles')
    op.drop_table('emotional_state')
    with op.batch_alter_table('world_choices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_choices_day_index'))

    op.drop_table('world_choices')
    op.drop_table('world_snapshots')
    op.drop_table('world_locations')
    with op.batch_alter_table('dog_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dog_memories_created_day'))
        batch_op.drop_index(batch_op.f('ix_dog_memories_dog_key'))
        batch_op.drop_index(batch_op.f('ix_dog_memories_scar_key'))

    op.drop_table('dog_memories')
    with op.batch_alter_table('npc_motives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_npc_motives_npc_key'))

    op.drop_table('npc_motives')
    with op.batch_alter_table('world_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_events_day_index'))

    op.drop_table('world_events')
    with op.batch_alter_table('ai_generated_pools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_generated_pools_pool_type'))
        batch_op.drop_index(batch_op.f('ix_ai_generated_pools_season'))

    op.drop_table('ai_generated_pools')
    with op.batch_alter_table('consequence_branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consequence_branches_branch_key'))

    op.drop_table('consequence_branches')
    with op.batch_alter_table('season_arcs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_season_arcs_season'))

    op.drop_table('season_arcs')
    op.drop_table('bestiary_sightings')
    with op.batch_alter_table('prologue_beats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prologue_beats_season'))

    op.drop_table('prologue_beats')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('emotional_consequence')
        batch_op.drop_column('trust_change')
        batch_op.drop_column('food_cost')
        batch_op.drop_column('npc_reactions_json')
        batch_op.drop_column('health_risk')
        batch_op.drop_column('water_cost')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water_cost', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('health_risk', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('npc_reactions_json', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('food_cost', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('trust_change', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('emotional_consequence', sa.TEXT(), nullable=False))

    op.create_table('prologue_beats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('season', sa.INTEGER(), nullable=False),
    sa.Column('day_index', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), nullable=False),
    sa.Column('block', sa.TEXT(), nullable=False),
    sa.Column('is_ai_generated', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prologue_beats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prologue_beats_season'), ['season'], unique=False)

    op.create_table('bestiary_sightings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('season', sa.VARCHAR(length=16), nullable=False),
    sa.Column('beast_key', sa.VARCHAR(length=32), nullable=False),
    sa.Column('day_index', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'beast_key', name=op.f('uq_bestiary_season_beast'))
    )
    op.create_table('season_arcs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('season', sa.INTEGER(), nullable=False),
    sa.Column('stage_index', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('purpose', sa.TEXT(), nullable=False),
    sa.Column('tone', sa.TEXT(), nullable=False),
    sa.Column('missions_json', sa.TEXT(), nullable=False),
    sa.Column('whisper_json', sa.TEXT(), nullable=False),
    sa.Column('teaser_json', sa.TEXT(), nullable=False),
    sa.Column('guest', sa.TEXT(), nullable=False),
    sa.Column('is_ai_generated', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('season_arcs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_season_arcs_season'), ['season'], unique=False)

    op.create_table('consequence_branches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('branch_key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('current_stage', sa.INTEGER(), nullable=False),
    sa.Column('history_json', sa.TEXT(), nullable=False),
    sa.Column('created_day', sa.INTEGER(), nullable=False),
    sa.Column('resolved', sa.BOOLEAN(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), nullable=False),
    sa.Column('stage_text', sa.TEXT(), nullable=False),
    sa.Column('choices_json', sa.TEXT(), nullable=False),
    sa.Column('resolution', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consequence_branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consequence_branches_branch_key'), ['branch_key'], unique=False)

    op.create_table('ai_generated_pools',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pool_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('season', sa.INTEGER(), nullable=False),
    sa.Column('phase', sa.VARCHAR(length=16), nullable=False),
    sa.Column('content_json', sa.TEXT(), nullable=False),
    sa.Column('is_ai_generated', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_generated_pools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_generated_pools_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_generated_pools_pool_type'), ['pool_type'], unique=False)

    op.create_table('world_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('day_index', sa.INTEGER(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('characters_involved', sa.TEXT(), nullable=False),
    sa.Column('locations_involved', sa.TEXT(), nullable=False),
    sa.Column('impact', sa.TEXT(), nullable=False),
    sa.Column('resolved', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_events_day_index'), ['day_index'], unique=False)

    op.create_table('npc_motives',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('npc_key', sa.VARCHAR(length=32), nullable=False),
    sa.Column('mood', sa.VARCHAR(length=16), nullable=False),
    sa.Column('motive_text', sa.TEXT(), nullable=False),
    sa.Column('action_text', sa.TEXT(), nullable=False),
    sa.Column('thought_pool_json', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('npc_motives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_npc_motives_npc_key'), ['npc_key'], unique=False)

    op.create_table('dog_memories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dog_key', sa.VARCHAR(length=32), nullable=False),
    sa.Column('kind', sa.VARCHAR(length=16), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=False),
    sa.Column('scar_key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('created_day', sa.INTEGER(), nullable=False),
    sa.Column('state', sa.VARCHAR(length=16), nullable=False),
    sa.Column('surfaced_day', sa.INTEGER(), nullable=True),
    sa.Column('healed_day', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dog_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dog_memories_scar_key'), ['scar_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_dog_memories_dog_key'), ['dog_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_dog_memories_created_day'), ['created_day'], unique=False)

    op.create_table('world_locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('atmosphere', sa.TEXT(), nullable=False),
    sa.Column('dangers', sa.TEXT(), nullable=False),
    sa.Column('resources', sa.TEXT(), nullable=False),
    sa.Column('created_day', sa.INTEGER(), nullable=False),
    sa.Column('last_visited_day', sa.INTEGER(), nullable=True),
    sa.Column('times_visited', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('metadata_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('world_snapshots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('day_index', sa.INTEGER(), nullable=False),
    sa.Column('mood', sa.VARCHAR(length=32), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=False),
    sa.Column('active_locations', sa.TEXT(), nullable=False),
    sa.Column('active_characters', sa.TEXT(), nullable=False),
    sa.Column('open_threads', sa.TEXT(), nullable=False),
    sa.Column('world_trend', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_index')
    )
    op.create_table('world_choices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('day_index', sa.INTEGER(), nullable=False),
    sa.Column('choice_text', sa.TEXT(), nullable=False),
    sa.Column('choice_tag', sa.VARCHAR(length=32), nullable=False),
    sa.Column('consequences_json', sa.TEXT(), nullable=False),
    sa.Column('characters_involved', sa.TEXT(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=120), nullable=True),
    sa.Column('votes_count', sa.INTEGER(), nullable=False),
    sa.Column('won', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world_choices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_choices_day_index'), ['day_index'], unique=False)

    op.create_table('emotional_state',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fatigue', sa.INTEGER(), nullable=False),
    sa.Column('hope', sa.INTEGER(), nullable=False),
    sa.Column('paranoia', sa.INTEGER(), nullable=False),
    sa.Column('last_updated_day', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('npc_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('npc_key', sa.VARCHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('personality', sa.TEXT(), nullable=False),
    sa.Column('speech_style', sa.TEXT(), nullable=False),
    sa.Column('appearance', sa.TEXT(), nullable=False),
    sa.Column('default_mood', sa.VARCHAR(length=16), nullable=False),
    sa.Column('is_ai_generated', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('npc_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_npc_profiles_npc_key'), ['npc_key'], unique=1)

    op.create_table('world_scars',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scar_key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('created_day', sa.INTEGER(), nullable=False),
    sa.Column('expires_day', sa.INTEGER(), nullable=True),
    sa.Column('strength', sa.INTEGER(), nullable=False),
    sa.Column('metadata_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world_scars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_scars_scar_key'), ['scar_key'], unique=False)

    op.create_table('world_characters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('role', sa.VARCHAR(length=32), nullable=False),
    sa.Column('personality', sa.TEXT(), nullable=False),
    sa.Column('flaw', sa.TEXT(), nullable=False),
    sa.Column('virtue', sa.TEXT(), nullable=False),
    sa.Column('moral_alignment', sa.VARCHAR(length=32), nullable=False),
    sa.Column('mood', sa.VARCHAR(length=32), nullable=False),
    sa.Column('trust_stay', sa.INTEGER(), nullable=False),
    sa.Column('created_day', sa.INTEGER(), nullable=False),
    sa.Column('last_seen_day', sa.INTEGER(), nullable=True),
    sa.Column('is_alive', sa.BOOLEAN(), nullable=False),
    sa.Column('metadata_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
