"""sync schema with current models

Revision ID: 4c9c12b66c56
Revises: 2d4f3fbc1a33
Create Date: 2026-09-17 08:37:58.627138

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4c9c12b66c56'
down_revision: str | Sequence[str] | None = '2d4f3fbc1a33'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lore_echoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lore_echoes_born_day'))
        batch_op.drop_index(batch_op.f('ix_lore_echoes_earliest_day'))

    op.drop_table('lore_echoes')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('calling')

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tie_entropy', sa.String(length=80), nullable=True))
        batch_op.drop_index(batch_op.f('ix_rounds_season'))
        batch_op.drop_column('cover_path')
        batch_op.drop_column('sealed')
        batch_op.drop_column('place')
        batch_op.drop_column('lore_summary')
        batch_op.drop_column('rule_commitment')
        batch_op.drop_column('season')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season', sa.VARCHAR(length=7), nullable=True))
        batch_op.add_column(sa.Column('rule_commitment', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('lore_summary', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('place', sa.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('sealed', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('cover_path', sa.VARCHAR(length=400), nullable=False))
        batch_op.create_index(batch_op.f('ix_rounds_season'), ['season'], unique=False)
        batch_op.drop_column('tie_entropy')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calling', sa.VARCHAR(length=32), nullable=True))

    op.create_table('lore_echoes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('born_day', sa.INTEGER(), nullable=False),
    sa.Column('source_day', sa.INTEGER(), nullable=False),
    sa.Column('kind', sa.VARCHAR(length=32), nullable=False),
    sa.Column('title', sa.VARCHAR(length=160), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('strength', sa.INTEGER(), nullable=False),
    sa.Column('earliest_day', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('surfaced_day', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lore_echoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lore_echoes_earliest_day'), ['earliest_day'], unique=False)
        batch_op.create_index(batch_op.f('ix_lore_echoes_born_day'), ['born_day'], unique=False)

    # ### end Alembic commands ###
