"""baseline schema matching current models

Revision ID: 917223d866c0
Revises: 
Create Date: 2026-08-23 13:03:10.439804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917223d866c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboard_pots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('nanotons', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month')
    )
    op.create_table('lore_echoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('born_day', sa.Integer(), nullable=False),
    sa.Column('source_day', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('earliest_day', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('surfaced_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lore_echoes_born_day'), 'lore_echoes', ['born_day'], unique=False)
    op.create_index(op.f('ix_lore_echoes_earliest_day'), 'lore_echoes', ['earliest_day'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('correct_picks', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=80), nullable=True),
    sa.Column('wallet_linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_address')
    )
    op.create_table('prepared_days',
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('day_index')
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'tallying', 'closed', name='roundstatus', native_enum=False), nullable=False),
    sa.Column('win_rule', sa.Enum('majority', 'minority', 'median', name='winrule', native_enum=False), nullable=False),
    sa.Column('rule_commitment', sa.String(length=128), nullable=False),
    sa.Column('chapter_title', sa.String(length=300), nullable=False),
    sa.Column('chapter_text', sa.Text(), nullable=False),
    sa.Column('lore_summary', sa.Text(), nullable=False),
    sa.Column('cover_path', sa.String(length=400), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('voting_ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tally_ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('winner_card', sa.Integer(), nullable=True),
    sa.Column('vote_counts_json', sa.Text(), nullable=True),
    sa.Column('announced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pot_nanotons', sa.BigInteger(), nullable=False),
    sa.Column('rake_nanotons', sa.BigInteger(), nullable=False),
    sa.Column('payouts_finalized', sa.Boolean(), nullable=False),
    sa.Column('epilogue_text', sa.String(length=700), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_index')
    )
    op.create_table('story_beats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('winning_title', sa.String(length=120), nullable=False),
    sa.Column('winning_text', sa.Text(), nullable=False),
    sa.Column('win_rule', sa.String(length=32), nullable=False),
    sa.Column('vote_counts', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_index')
    )
    op.create_table('wallet_dialogs',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('since', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('watcher_state',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(length=400), nullable=False),
    sa.Column('consequence', sa.Text(), nullable=False),
    sa.Column('tag', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'position', name='uq_card_round_pos')
    )
    op.create_index(op.f('ix_cards_round_id'), 'cards', ['round_id'], unique=False)
    op.create_table('incomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount_stars', sa.Integer(), nullable=False),
    sa.Column('amount_nanotons', sa.BigInteger(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('unit_ref', sa.String(length=80), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_ref')
    )
    op.create_index(op.f('ix_incomes_player_id'), 'incomes', ['player_id'], unique=False)
    op.create_index(op.f('ix_incomes_round_id'), 'incomes', ['round_id'], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount_nanotons', sa.BigInteger(), nullable=False),
    sa.Column('dest_address', sa.String(length=80), nullable=False),
    sa.Column('tx_hash', sa.String(length=80), nullable=True),
    sa.Column('network', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('alerted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_round_id'), 'payouts', ['round_id'], unique=False)
    op.create_table('revote_grants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('unit_ref', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_ref')
    )
    op.create_index(op.f('ix_revote_grants_player_id'), 'revote_grants', ['player_id'], unique=False)
    op.create_index(op.f('ix_revote_grants_round_id'), 'revote_grants', ['round_id'], unique=False)
    op.create_table('stakes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_nanotons', sa.BigInteger(), nullable=False),
    sa.Column('tx_hash', sa.String(length=80), nullable=False),
    sa.Column('memo', sa.String(length=64), nullable=False),
    sa.Column('network', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'player_id', name='uq_stake_round_player'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_index(op.f('ix_stakes_player_id'), 'stakes', ['player_id'], unique=False)
    op.create_index(op.f('ix_stakes_round_id'), 'stakes', ['round_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('card_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'player_id', name='uq_vote_round_player')
    )
    op.create_index(op.f('ix_votes_player_id'), 'votes', ['player_id'], unique=False)
    op.create_index(op.f('ix_votes_round_id'), 'votes', ['round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_round_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_player_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_stakes_round_id'), table_name='stakes')
    op.drop_index(op.f('ix_stakes_player_id'), table_name='stakes')
    op.drop_table('stakes')
    op.drop_index(op.f('ix_revote_grants_round_id'), table_name='revote_grants')
    op.drop_index(op.f('ix_revote_grants_player_id'), table_name='revote_grants')
    op.drop_table('revote_grants')
    op.drop_index(op.f('ix_payouts_round_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_incomes_round_id'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_player_id'), table_name='incomes')
    op.drop_table('incomes')
    op.drop_index(op.f('ix_cards_round_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_table('watcher_state')
    op.drop_table('wallet_dialogs')
    op.drop_table('story_beats')
    op.drop_table('rounds')
    op.drop_table('prepared_days')
    op.drop_table('players')
    op.drop_index(op.f('ix_lore_echoes_earliest_day'), table_name='lore_echoes')
    op.drop_index(op.f('ix_lore_echoes_born_day'), table_name='lore_echoes')
    op.drop_table('lore_echoes')
    op.drop_table('leaderboard_pots')
    op.drop_table('chats')
    # ### end Alembic commands ###
