"""rounds tie note

Revision ID: dc55f0bdf07d
Revises: 917223d866c0
Create Date: 2026-08-23 16:49:37.206777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc55f0bdf07d'
down_revision: Union[str, Sequence[str], None] = '917223d866c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('tie_note', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'tie_note')
    # ### end Alembic commands ###
