"""add stake/payout enums and check constraints

Revision ID: dec4728c5f0c
Revises: f6a7b8c9d0e1
Create Date: 2026-09-04 11:43:23.196845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec4728c5f0c'
down_revision: Union[str, Sequence[str], None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consequence_branches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_key', sa.String(length=64), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('history_json', sa.Text(), nullable=False),
    sa.Column('created_day', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('stage_text', sa.Text(), nullable=False),
    sa.Column('choices_json', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consequence_branches_branch_key'), 'consequence_branches', ['branch_key'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('keeper_note', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_player_id'), 'disputes', ['player_id'], unique=False)
    op.create_index(op.f('ix_disputes_round_id'), 'disputes', ['round_id'], unique=False)
    op.create_table('emotional_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fatigue', sa.Integer(), nullable=False),
    sa.Column('hope', sa.Integer(), nullable=False),
    sa.Column('paranoia', sa.Integer(), nullable=False),
    sa.Column('last_updated_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('npc_motives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('npc_key', sa.String(length=32), nullable=False),
    sa.Column('mood', sa.String(length=16), nullable=False),
    sa.Column('motive_text', sa.Text(), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('thought_pool_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npc_motives_npc_key'), 'npc_motives', ['npc_key'], unique=False)
    op.create_table('npc_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('npc_key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('speech_style', sa.Text(), nullable=False),
    sa.Column('appearance', sa.Text(), nullable=False),
    sa.Column('default_mood', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npc_profiles_npc_key'), 'npc_profiles', ['npc_key'], unique=True)
    op.create_table('pack_fund_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_type', sa.String(length=8), nullable=False),
    sa.Column('amount_nanotons', sa.BigInteger(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pack_fund_ledger_round_id'), 'pack_fund_ledger', ['round_id'], unique=False)
    op.create_table('pack_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hunger', sa.Integer(), nullable=False),
    sa.Column('thirst', sa.Integer(), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('alive_count', sa.Integer(), nullable=False),
    sa.Column('last_updated_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prologue_beats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('block', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prologue_beats_season'), 'prologue_beats', ['season'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=False),
    sa.Column('referred_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_id')
    )
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('season_arcs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('tone', sa.Text(), nullable=False),
    sa.Column('missions_json', sa.Text(), nullable=False),
    sa.Column('whisper_json', sa.Text(), nullable=False),
    sa.Column('teaser_json', sa.Text(), nullable=False),
    sa.Column('guest', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_arcs_season'), 'season_arcs', ['season'], unique=False)
    op.create_table('world_characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('flaw', sa.Text(), nullable=False),
    sa.Column('virtue', sa.Text(), nullable=False),
    sa.Column('moral_alignment', sa.String(length=32), nullable=False),
    sa.Column('mood', sa.String(length=32), nullable=False),
    sa.Column('trust_stay', sa.Integer(), nullable=False),
    sa.Column('created_day', sa.Integer(), nullable=False),
    sa.Column('last_seen_day', sa.Integer(), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('world_choices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('choice_text', sa.Text(), nullable=False),
    sa.Column('choice_tag', sa.String(length=32), nullable=False),
    sa.Column('consequences_json', sa.Text(), nullable=False),
    sa.Column('characters_involved', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('votes_count', sa.Integer(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_choices_day_index'), 'world_choices', ['day_index'], unique=False)
    op.create_table('world_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('characters_involved', sa.Text(), nullable=False),
    sa.Column('locations_involved', sa.Text(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_events_day_index'), 'world_events', ['day_index'], unique=False)
    op.create_table('world_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('atmosphere', sa.Text(), nullable=False),
    sa.Column('dangers', sa.Text(), nullable=False),
    sa.Column('resources', sa.Text(), nullable=False),
    sa.Column('created_day', sa.Integer(), nullable=False),
    sa.Column('last_visited_day', sa.Integer(), nullable=True),
    sa.Column('times_visited', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('world_scars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scar_key', sa.String(length=64), nullable=False),
    sa.Column('created_day', sa.Integer(), nullable=False),
    sa.Column('expires_day', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_scars_scar_key'), 'world_scars', ['scar_key'], unique=False)
    op.create_table('world_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('mood', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('active_locations', sa.Text(), nullable=False),
    sa.Column('active_characters', sa.Text(), nullable=False),
    sa.Column('open_threads', sa.Text(), nullable=False),
    sa.Column('world_trend', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_index')
    )
    op.create_table('leaderboard_claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'kind', 'period', name='uq_leaderboard_claims_player_kind_period')
    )
    op.add_column('cards', sa.Column('food_cost', sa.Integer(), nullable=False))
    op.add_column('cards', sa.Column('water_cost', sa.Integer(), nullable=False))
    op.add_column('cards', sa.Column('health_risk', sa.Integer(), nullable=False))
    op.add_column('cards', sa.Column('trust_change', sa.Integer(), nullable=False))
    op.add_column('cards', sa.Column('emotional_consequence', sa.Text(), nullable=False))
    op.add_column('cards', sa.Column('npc_reactions_json', sa.Text(), nullable=False))
    # SQLite doesn't support ALTER COLUMN TYPE for enums; skip for SQLite
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        op.alter_column('payouts', 'status',
                   existing_type=sa.VARCHAR(length=16),
                   type_=sa.Enum('pending', 'sending', 'sent', 'failed', 'dismissed', name='payoutstatus'),
                   existing_nullable=False)
    op.create_check_constraint('ck_payout_positive_amount', 'payouts', 'amount_nanotons > 0')
    op.add_column('players', sa.Column('wallet_verified', sa.Boolean(), nullable=False))
    op.add_column('players', sa.Column('wallet_verify_code', sa.String(length=16), nullable=True))
    op.add_column('players', sa.Column('wallet_verify_created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('players', sa.Column('dm_subscribed', sa.Boolean(), nullable=False))
    op.add_column('players', sa.Column('current_streak', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('best_streak', sa.Integer(), nullable=False))
    op.add_column('rounds', sa.Column('money_mode', sa.Boolean(), nullable=False))
    # SQLite doesn't support ALTER COLUMN TYPE for enums; skip for SQLite
    if bind.dialect.name != 'sqlite':
        op.alter_column('stakes', 'status',
                   existing_type=sa.VARCHAR(length=16),
                   type_=sa.Enum('pending', 'confirmed', 'rejected', 'refunded', name='stakestatus'),
                   existing_nullable=False)
    op.create_check_constraint('ck_stake_positive_amount', 'stakes', 'amount_nanotons > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_stake_positive_amount', 'stakes', type_='check')
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        op.alter_column('stakes', 'status',
                   existing_type=sa.Enum('pending', 'confirmed', 'rejected', 'refunded', name='stakestatus'),
                   type_=sa.VARCHAR(length=16),
                   existing_nullable=False)
    op.drop_column('rounds', 'money_mode')
    op.drop_column('players', 'best_streak')
    op.drop_column('players', 'current_streak')
    op.drop_column('players', 'dm_subscribed')
    op.drop_column('players', 'wallet_verify_created')
    op.drop_column('players', 'wallet_verify_code')
    op.drop_column('players', 'wallet_verified')
    op.drop_constraint('ck_payout_positive_amount', 'payouts', type_='check')
    if bind.dialect.name != 'sqlite':
        op.alter_column('payouts', 'status',
                   existing_type=sa.Enum('pending', 'sending', 'sent', 'failed', 'dismissed', name='payoutstatus'),
                   type_=sa.VARCHAR(length=16),
                   existing_nullable=False)
    op.drop_column('cards', 'npc_reactions_json')
    op.drop_column('cards', 'emotional_consequence')
    op.drop_column('cards', 'trust_change')
    op.drop_column('cards', 'health_risk')
    op.drop_column('cards', 'water_cost')
    op.drop_column('cards', 'food_cost')
    op.drop_table('leaderboard_claims')
    op.drop_table('world_snapshots')
    op.drop_index(op.f('ix_world_scars_scar_key'), table_name='world_scars')
    op.drop_table('world_scars')
    op.drop_table('world_locations')
    op.drop_index(op.f('ix_world_events_day_index'), table_name='world_events')
    op.drop_table('world_events')
    op.drop_index(op.f('ix_world_choices_day_index'), table_name='world_choices')
    op.drop_table('world_choices')
    op.drop_table('world_characters')
    op.drop_index(op.f('ix_season_arcs_season'), table_name='season_arcs')
    op.drop_table('season_arcs')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_prologue_beats_season'), table_name='prologue_beats')
    op.drop_table('prologue_beats')
    op.drop_table('pack_state')
    op.drop_index(op.f('ix_pack_fund_ledger_round_id'), table_name='pack_fund_ledger')
    op.drop_table('pack_fund_ledger')
    op.drop_index(op.f('ix_npc_profiles_npc_key'), table_name='npc_profiles')
    op.drop_table('npc_profiles')
    op.drop_index(op.f('ix_npc_motives_npc_key'), table_name='npc_motives')
    op.drop_table('npc_motives')
    op.drop_table('emotional_state')
    op.drop_index(op.f('ix_disputes_round_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_player_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_consequence_branches_branch_key'), table_name='consequence_branches')
    op.drop_table('consequence_branches')
    # ### end Alembic commands ###
